/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_api_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_api_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_api_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_session_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_session_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Workspaces */
        get: operations["list_workspaces_api_workspaces_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspace_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Workspace */
        get: operations["get_workspace_api_workspaces__workspace_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspace_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Members */
        get: operations["list_members_api_workspaces__workspace_id__members_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspace_id}/members/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Member */
        delete: operations["remove_member_api_workspaces__workspace_id__members__user_id__delete"];
        options?: never;
        head?: never;
        /** Update Member */
        patch: operations["update_member_api_workspaces__workspace_id__members__user_id__patch"];
        trace?: never;
    };
    "/api/workspaces/{workspace_id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents */
        get: operations["list_documents_api_workspaces__workspace_id__documents_get"];
        put?: never;
        /** Upload Document */
        post: operations["upload_document_api_workspaces__workspace_id__documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspace_id}/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Document Detail */
        get: operations["document_detail_api_workspaces__workspace_id__documents__document_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Withdraw Document */
        patch: operations["withdraw_document_api_workspaces__workspace_id__documents__document_id__patch"];
        trace?: never;
    };
    "/api/workspaces/{workspace_id}/documents/{document_id}/versions/{version_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Preview */
        get: operations["preview_api_workspaces__workspace_id__documents__document_id__versions__version_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspace_id}/documents/{document_id}/versions/{version_id}/original": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Original */
        get: operations["original_api_workspaces__workspace_id__documents__document_id__versions__version_id__original_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspace_id}/retrieval": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search */
        post: operations["search_api_workspaces__workspace_id__retrieval_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspace_id}/retrieval/{trace_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trace Detail */
        get: operations["trace_detail_api_workspaces__workspace_id__retrieval__trace_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspace_id}/runs/{run_id}/attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Attempt */
        post: operations["create_attempt_api_workspaces__workspace_id__runs__run_id__attempts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspace_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Messages */
        get: operations["list_messages_api_workspaces__workspace_id__messages_get"];
        put?: never;
        /** Create Message */
        post: operations["create_message_api_workspaces__workspace_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspace_id}/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run Detail */
        get: operations["run_detail_api_workspaces__workspace_id__runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspace_id}/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel */
        post: operations["cancel_api_workspaces__workspace_id__runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspace_id}/runs/{run_id}/development-handoff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export */
        get: operations["export_api_workspaces__workspace_id__runs__run_id__development_handoff_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspace_id}/runs/{run_id}/development-handoff/{handoff_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Contribute */
        post: operations["contribute_api_workspaces__workspace_id__runs__run_id__development_handoff__handoff_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspace_id}/message-imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Messages */
        post: operations["import_messages_api_workspaces__workspace_id__message_imports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspace_id}/messages/{message_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detail */
        get: operations["detail_api_workspaces__workspace_id__messages__message_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspace_id}/messages/{message_id}/labels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Labels */
        put: operations["labels_api_workspaces__workspace_id__messages__message_id__labels_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspace_id}/messages/{message_id}/process": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start */
        post: operations["start_api_workspaces__workspace_id__messages__message_id__process_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspace_id}/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Settings */
        get: operations["settings_api_workspaces__workspace_id__settings_get"];
        /** Change Defaults */
        put: operations["change_defaults_api_workspaces__workspace_id__settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspace_id}/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Usage */
        get: operations["usage_api_workspaces__workspace_id__usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspace_id}/runs/{run_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review */
        post: operations["review_api_workspaces__workspace_id__runs__run_id__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AttemptInput */
        AttemptInput: {
            /**
             * Action
             * @enum {string}
             */
            action: "retry" | "clarify";
            /** Clarification */
            clarification?: string | null;
        };
        /** AttemptSummary */
        AttemptSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Number */
            number: number;
            /** Kind */
            kind: string;
            /** State */
            state: string;
            /** Outcome */
            outcome: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** Body_import_messages_api_workspaces__workspace_id__message_imports_post */
        Body_import_messages_api_workspaces__workspace_id__message_imports_post: {
            /** File */
            file: string;
        };
        /** Body_upload_document_api_workspaces__workspace_id__documents_post */
        Body_upload_document_api_workspaces__workspace_id__documents_post: {
            /** File */
            file: string;
            /** Document Id */
            document_id?: string | null;
        };
        /** CallSummary */
        CallSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Operation */
            operation: string;
            /** Provider */
            provider: string;
            /** Model */
            model: string;
            /** Revision */
            revision: string;
            /** Status */
            status: string;
            /** Input Tokens */
            input_tokens: number | null;
            /** Duration Ms */
            duration_ms: number | null;
            /** Api Cost Usd */
            api_cost_usd: number | null;
            /** Error Code */
            error_code: string | null;
        };
        /** CitationInput */
        CitationInput: {
            /**
             * Chunk Id
             * Format: uuid
             */
            chunk_id: string;
            /** Quote */
            quote: string;
        };
        /** CitedPassage */
        CitedPassage: {
            /**
             * Chunk Id
             * Format: uuid
             */
            chunk_id: string;
            /**
             * Version Id
             * Format: uuid
             */
            version_id: string;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Title */
            title: string;
            /** Section */
            section: string;
            /** Text */
            text: string;
            /** Start Offset */
            start_offset: number;
            /** End Offset */
            end_offset: number;
            /** Checksum */
            checksum: string;
            /** Cosine Similarity */
            cosine_similarity: number | null;
            /** Rank Score */
            rank_score: number;
            /** Quote */
            quote: string;
            /** Quote Start */
            quote_start: number;
            /** Quote End */
            quote_end: number;
        };
        /** Credentials */
        Credentials: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** DecisionSummary */
        DecisionSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Actor Id
             * Format: uuid
             */
            actor_id: string;
            /** Action */
            action: string;
            /** Reason */
            reason: string;
            /** Response */
            response: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Revision */
            revision: number;
        };
        /** DevelopmentContext */
        DevelopmentContext: {
            /** Original */
            original: string;
            /** Language */
            language: string;
            /** Instruction */
            instruction: string;
            /** Prompt Version */
            prompt_version: string;
            /** Sources */
            sources: components["schemas"]["RetrievedPassage"][];
        };
        /** DevelopmentResponse */
        DevelopmentResponse: {
            /** Context Hash */
            context_hash: string;
            /** Answer */
            answer: string;
            /** Citations */
            citations: components["schemas"]["CitationInput"][];
            /**
             * Review Category
             * @default ordinary
             * @enum {string}
             */
            review_category: "ordinary" | "policy_exception" | "conflicting_evidence";
        };
        /** DocumentDetail */
        DocumentDetail: {
            document: components["schemas"]["DocumentSummary"];
            /** Versions */
            versions: components["schemas"]["VersionSummary"][];
        };
        /** DocumentPage */
        DocumentPage: {
            /** Items */
            items: components["schemas"]["DocumentSummary"][];
            /** Total */
            total: number;
        };
        /** DocumentSummary */
        DocumentSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Withdrawn */
            withdrawn: boolean;
            /** Active Version Id */
            active_version_id: string | null;
            /** Desired Version Id */
            desired_version_id: string | null;
            /** Version Number */
            version_number: number;
            /** Job Status */
            job_status: string | null;
            /** Error Code */
            error_code: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HandoffExport */
        HandoffExport: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Context Hash */
            context_hash: string;
            /** Provider */
            provider: string;
            /** Prompt Version */
            prompt_version: string;
            context: components["schemas"]["DevelopmentContext"];
        };
        /** HandoffSummary */
        HandoffSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Context Hash */
            context_hash: string;
            /** Provider */
            provider: string;
            /** Prompt Version */
            prompt_version: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Submitted At */
            submitted_at: string | null;
            /** Contributor Id */
            contributor_id: string | null;
            /** Handoff Elapsed Ms */
            handoff_elapsed_ms: number | null;
            /**
             * Timing Status
             * @enum {string}
             */
            timing_status: "pending" | "recorded" | "clock_anomaly";
        };
        /** ImportResult */
        ImportResult: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Filename */
            filename: string;
            /** Message Count */
            message_count: number;
        };
        /** Labels */
        Labels: {
            /** Labels */
            labels?: string[];
        };
        /** MemberResponse */
        MemberResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Display Name */
            display_name: string;
            /**
             * Role
             * @enum {string}
             */
            role: "viewer" | "operator" | "admin";
        };
        /** MessageCreated */
        MessageCreated: {
            /**
             * Message Id
             * Format: uuid
             */
            message_id: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
        };
        /** MessageInput */
        MessageInput: {
            /** Original */
            original: string;
            /**
             * Language
             * @enum {string}
             */
            language: "en" | "ja" | "zh";
        };
        /** MessagePage */
        MessagePage: {
            /** Items */
            items: components["schemas"]["MessageSummary"][];
            /** Total */
            total: number;
        };
        /** MessageSummary */
        MessageSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Original */
            original: string;
            /** Language */
            language: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Run Id */
            run_id: string | null;
            /** Labels */
            labels: string[];
            /** State */
            state: string;
            /** Outcome */
            outcome: string | null;
            /** Error Code */
            error_code: string | null;
        };
        /** ModelUsage */
        ModelUsage: {
            /** Calls */
            calls: number;
            /** Succeeded */
            succeeded: number;
            /** Failed */
            failed: number;
            /** Uncertain */
            uncertain: number;
            /** Started */
            started: number;
            /** Input Tokens */
            input_tokens: number;
            /** Missing Tokens */
            missing_tokens: number;
            /** Recorded Cost Usd */
            recorded_cost_usd: number;
            /** Missing Cost */
            missing_cost: number;
            /** Recorded Duration Ms */
            recorded_duration_ms: number;
            /** Missing Duration */
            missing_duration: number;
            /** Operation */
            operation: string;
            /** Provider */
            provider: string;
            /** Model */
            model: string;
            /** Revision */
            revision: string;
        };
        /** ProcessingDefaults */
        ProcessingDefaults: {
            /**
             * Default Language
             * @enum {string}
             */
            default_language: "en" | "ja" | "zh";
        };
        /** PublicUser */
        PublicUser: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Display Name */
            display_name: string;
        };
        /** QueryInput */
        QueryInput: {
            /** Query */
            query: string;
            /**
             * Limit
             * @default 5
             */
            limit: number;
            /**
             * Strategy
             * @default vector_rerank
             * @enum {string}
             */
            strategy: "vector" | "bm25" | "hybrid" | "vector_rerank" | "hybrid_rerank";
        };
        /** RetrievalResult */
        RetrievalResult: {
            /**
             * Trace Id
             * Format: uuid
             */
            trace_id: string;
            /** Duration Ms */
            duration_ms: number;
            /** Status */
            status: string;
            /** Results */
            results: components["schemas"]["RetrievedPassage"][];
        };
        /** RetrievedPassage */
        RetrievedPassage: {
            /**
             * Chunk Id
             * Format: uuid
             */
            chunk_id: string;
            /**
             * Version Id
             * Format: uuid
             */
            version_id: string;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Title */
            title: string;
            /** Section */
            section: string;
            /** Text */
            text: string;
            /** Start Offset */
            start_offset: number;
            /** End Offset */
            end_offset: number;
            /** Checksum */
            checksum: string;
            /** Cosine Similarity */
            cosine_similarity: number | null;
            /** Rank Score */
            rank_score: number;
        };
        /** ReviewInput */
        ReviewInput: {
            /**
             * Action
             * @enum {string}
             */
            action: "approve" | "edit" | "reject" | "clarify";
            /** Reason */
            reason: string;
            /** Expected Revision */
            expected_revision: number;
            /** Draft Hash */
            draft_hash: string;
            /** Response */
            response?: string | null;
        };
        /** RoleChange */
        RoleChange: {
            /**
             * Role
             * @enum {string}
             */
            role: "viewer" | "operator" | "admin";
        };
        /** RunDetail */
        RunDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Message Id
             * Format: uuid
             */
            message_id: string;
            /** Parent Run Id */
            parent_run_id: string | null;
            /**
             * Creator Id
             * Format: uuid
             */
            creator_id: string;
            /** Attempt Number */
            attempt_number: number;
            /** Input Text */
            input_text: string;
            /** Clarification */
            clarification: string | null;
            /** Attempts */
            attempts: components["schemas"]["AttemptSummary"][];
            /**
             * Latest Run Id
             * Format: uuid
             */
            latest_run_id: string;
            /** Original */
            original: string;
            /** Language */
            language: string;
            /** State */
            state: string;
            /** Outcome */
            outcome: string | null;
            /** Review Kind */
            review_kind: string;
            /** Review Version */
            review_version: number;
            /** Draft Hash */
            draft_hash: string | null;
            /** Reviewed Response */
            reviewed_response: string | null;
            review: components["schemas"]["DecisionSummary"] | null;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Error Code */
            error_code: string | null;
            /** Draft */
            draft: string | null;
            /** Citations */
            citations: components["schemas"]["CitedPassage"][];
            handoff: components["schemas"]["HandoffSummary"] | null;
            /** Steps */
            steps: components["schemas"]["StepSummary"][];
            /** Model Calls */
            model_calls: components["schemas"]["CallSummary"][];
            /** Retrieval Id */
            retrieval_id: string | null;
            /**
             * Support Status
             * @default not_verified
             */
            support_status: string;
        };
        /** SavedMessage */
        SavedMessage: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Original */
            original: string;
            /** Language */
            language: string;
            /** Labels */
            labels: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Import Filename */
            import_filename: string | null;
            /** Latest Run Id */
            latest_run_id: string | null;
        };
        /** SessionResponse */
        SessionResponse: {
            user: components["schemas"]["PublicUser"] | null;
            /** Csrf Token */
            csrf_token: string;
        };
        /** SourcePreview */
        SourcePreview: {
            /**
             * Version Id
             * Format: uuid
             */
            version_id: string;
            /** Text */
            text: string;
            /** Offset */
            offset: number;
            /** Total Characters */
            total_characters: number;
            /** Checksum */
            checksum: string;
            /** Active */
            active: boolean;
            /** Withdrawn */
            withdrawn: boolean;
        };
        /** StepSummary */
        StepSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Node */
            node: string;
            /** Status */
            status: string;
            /** Duration Ms */
            duration_ms: number | null;
            /** Job Attempt */
            job_attempt: number;
            /** Error Code */
            error_code: string | null;
        };
        /** TraceCandidate */
        TraceCandidate: {
            /**
             * Chunk Id
             * Format: uuid
             */
            chunk_id: string;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /**
             * Version Id
             * Format: uuid
             */
            version_id: string;
            /** Title */
            title: string;
            /** Section */
            section: string;
            /** Start Offset */
            start_offset: number;
            /** Currently Active */
            currently_active: boolean;
            /** Vector Rank */
            vector_rank?: number | null;
            /** Cosine Similarity */
            cosine_similarity?: number | null;
            /** Bm25 Rank */
            bm25_rank?: number | null;
            /** Bm25 Score */
            bm25_score?: number | null;
            /** Fusion Rank */
            fusion_rank?: number | null;
            /** Fusion Score */
            fusion_score?: number | null;
            /** Reranker Rank */
            reranker_rank?: number | null;
            /** Reranker Score */
            reranker_score?: number | null;
            /** Final Rank */
            final_rank?: number | null;
            /**
             * Selected For Reranker
             * @default false
             */
            selected_for_reranker: boolean;
            /** Exclusion */
            exclusion?: string | null;
        };
        /** TraceDetail */
        TraceDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Query */
            query: string;
            /** Status */
            status: string;
            /** Strategy */
            strategy: string;
            /** Duration Ms */
            duration_ms: number | null;
            /** Error Code */
            error_code: string | null;
            /** Trace Version */
            trace_version: string | null;
            /** Phase */
            phase: string;
            /** Candidate Queries Ms */
            candidate_queries_ms: number | null;
            /** Parameters */
            parameters: {
                [key: string]: number | string;
            };
            /** Candidates */
            candidates: components["schemas"]["TraceCandidate"][];
        };
        /** UploadResult */
        UploadResult: {
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /**
             * Version Id
             * Format: uuid
             */
            version_id: string;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
        };
        /** UsageReport */
        UsageReport: {
            /**
             * Since
             * Format: date-time
             */
            since: string;
            /**
             * Until
             * Format: date-time
             */
            until: string;
            /** Days */
            days: number;
            totals: components["schemas"]["UsageTotals"];
            /** Models */
            models: components["schemas"]["ModelUsage"][];
            /** More Models */
            more_models: boolean;
        };
        /** UsageTotals */
        UsageTotals: {
            /** Calls */
            calls: number;
            /** Succeeded */
            succeeded: number;
            /** Failed */
            failed: number;
            /** Uncertain */
            uncertain: number;
            /** Started */
            started: number;
            /** Input Tokens */
            input_tokens: number;
            /** Missing Tokens */
            missing_tokens: number;
            /** Recorded Cost Usd */
            recorded_cost_usd: number;
            /** Missing Cost */
            missing_cost: number;
            /** Recorded Duration Ms */
            recorded_duration_ms: number;
            /** Missing Duration */
            missing_duration: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VersionSummary */
        VersionSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Number */
            number: number;
            /** Filename */
            filename: string;
            /** Checksum */
            checksum: string;
            /** Indexed At */
            indexed_at: string | null;
            /** Job Status */
            job_status: string;
            /** Error Code */
            error_code: string | null;
        };
        /** Withdrawal */
        Withdrawal: {
            /** Withdrawn */
            withdrawn: boolean;
        };
        /** WorkspaceResponse */
        WorkspaceResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Role
             * @enum {string}
             */
            role: "viewer" | "operator" | "admin";
            /**
             * Default Language
             * @default en
             * @enum {string}
             */
            default_language: "en" | "ja" | "zh";
        };
        /** WorkspaceSettings */
        WorkspaceSettings: {
            /**
             * Default Language
             * @enum {string}
             */
            default_language: "en" | "ja" | "zh";
            /** Generation Mode */
            generation_mode: string;
            /** Automatic Generation Available */
            automatic_generation_available: boolean;
            /** Embedding Model */
            embedding_model: string;
            /** Embedding Revision */
            embedding_revision: string;
            /** Reranker Model */
            reranker_model: string;
            /** Reranker Revision */
            reranker_revision: string;
            /** Retrieval Strategy */
            retrieval_strategy: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    live_api_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    ready_api_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_session_api_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
        };
    };
    login_api_session_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_session_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_workspaces_api_workspaces_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceResponse"][];
                };
            };
        };
    };
    get_workspace_api_workspaces__workspace_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_members_api_workspaces__workspace_id__members_get: {
        parameters: {
            query?: {
                offset?: number;
            };
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_member_api_workspaces__workspace_id__members__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_member_api_workspaces__workspace_id__members__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleChange"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_api_workspaces__workspace_id__documents_get: {
        parameters: {
            query?: {
                search?: string;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_document_api_workspaces__workspace_id__documents_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_api_workspaces__workspace_id__documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    document_detail_api_workspaces__workspace_id__documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    withdraw_document_api_workspaces__workspace_id__documents__document_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
                document_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Withdrawal"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_api_workspaces__workspace_id__documents__document_id__versions__version_id__get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path: {
                workspace_id: string;
                document_id: string;
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourcePreview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    original_api_workspaces__workspace_id__documents__document_id__versions__version_id__original_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
                document_id: string;
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_workspaces__workspace_id__retrieval_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetrievalResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trace_detail_api_workspaces__workspace_id__retrieval__trace_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
                trace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_attempt_api_workspaces__workspace_id__runs__run_id__attempts_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                workspace_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttemptInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_messages_api_workspaces__workspace_id__messages_get: {
        parameters: {
            query?: {
                search?: string;
                offset?: number;
                limit?: number;
                view?: "all" | "unprocessed" | "attention" | "ready" | "processing" | "failed";
                label?: string;
            };
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessagePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_message_api_workspaces__workspace_id__messages_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_detail_api_workspaces__workspace_id__runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_api_workspaces__workspace_id__runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_api_workspaces__workspace_id__runs__run_id__development_handoff_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HandoffExport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    contribute_api_workspaces__workspace_id__runs__run_id__development_handoff__handoff_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
                run_id: string;
                handoff_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DevelopmentResponse"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_messages_api_workspaces__workspace_id__message_imports_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_messages_api_workspaces__workspace_id__message_imports_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detail_api_workspaces__workspace_id__messages__message_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
                message_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedMessage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    labels_api_workspaces__workspace_id__messages__message_id__labels_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
                message_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Labels"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedMessage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_api_workspaces__workspace_id__messages__message_id__process_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
                message_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    settings_api_workspaces__workspace_id__settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceSettings"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_defaults_api_workspaces__workspace_id__settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProcessingDefaults"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceSettings"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    usage_api_workspaces__workspace_id__usage_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_api_workspaces__workspace_id__runs__run_id__review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
