"""Extract facts without importing or executing application code."""
import ast
import json
from collections import Counter

from doc_sources import files, safe_path


def render(root):
    names = files(root)
    counts = Counter("/".join(n.split("/")[:-1][:3]) for n in names
                     if n.startswith(("backend/app/", "frontend/src/")) and not n.endswith(".md"))
    tree = ast.parse(safe_path(root, "scripts/manage.py").read_text(encoding="utf-8-sig"))
    commands = []
    for node in ast.walk(tree):
        if isinstance(node, ast.Call) and isinstance(node.func, ast.Attribute) and node.func.attr == "add_argument":
            if node.args and isinstance(node.args[0], ast.Constant) and node.args[0].value == "command":
                commands = ast.literal_eval(next(k.value for k in node.keywords if k.arg == "choices"))
    if not isinstance(commands, (list, tuple)) or not commands or not all(isinstance(c, str) for c in commands):
        raise ValueError("Cannot extract literal manage.py command choices; update the generator")
    package = json.loads(safe_path(root, "frontend/package.json").read_text(encoding="utf-8-sig"))
    if not isinstance(package, dict) or not isinstance(package.get("scripts", {}), dict):
        raise ValueError("frontend/package.json scripts must be an object")
    lines = ["# Generated source reference", "", "Generated by `python scripts/docs_freshness.py generate`. Do not edit.",
             "Paths and commands are source facts, not evidence that a feature or command succeeds.",
             "See [architecture](../ARCHITECTURE.md) for responsibilities and runtime data flow.", "",
             "## Current source groups", "", "| Path | Source files |", "| --- | ---: |"]
    lines += [f"| `{path}/` | {count} |" for path, count in sorted(counts.items())]
    lines += ["", "## Backend module directories", ""]
    modules = sorted({n.split("/")[3] for n in names if n.startswith("backend/app/modules/") and len(n.split("/")) > 4})
    lines += [f"- `backend/app/modules/{name}/`" for name in modules]
    lines += ["", "## Developer dispatcher commands", "", "```text"]
    lines += [f"python scripts/manage.py {command}" for command in sorted(commands)]
    lines += ["```", "", "## Frontend npm scripts", "", "```text"]
    lines += [f"{name}: {command}" for name, command in sorted(package.get("scripts", {}).items())]
    lines += ["```", "", "## Documentation maintenance", "", "```text",
              "python scripts/docs_freshness.py garden", "python scripts/docs_freshness.py generate",
              "python scripts/docs_freshness.py check", "python scripts/docs_freshness.py acknowledge --help", "```", ""]
    return "\n".join(lines)
